export interface CareerPath {
  id: string;
  name: string;
  summary: string;
  requiredSubjects: string[];
  relatedSkills: string[];
  educationPath: string | null;
  sourceUrl: string | null;
  sourceLabel: string | null;
  lastVerifiedAt: Date | null;
}

/**
 * Career information is read entirely from the `career_paths` table — never
 * generated by the LLM at request time. Career guidance is exactly the kind
 * of content where a plausible-sounding fabrication (a wrong required subject,
 * an invented salary figure) is genuinely harmful and hard for a student to
 * catch, so this module is a thin, honest read path with no generation.
 */
export interface CareerRepository {
  list(): Promise<CareerPath[]>;
  find(id: string): Promise<CareerPath | null>;
}

const STALE_AFTER_DAYS = 365;

export function isStale(path: CareerPath, now = new Date()): boolean {
  if (!path.lastVerifiedAt) return true;
  return (now.getTime() - path.lastVerifiedAt.getTime()) / 86_400_000 > STALE_AFTER_DAYS;
}

/**
 * Presentation-layer guard: a career entry with no source citation should
 * never be shown as if it were verified fact. This is the check the API route
 * runs before returning a row, not a UI-only nicety.
 */
export function isPresentable(path: CareerPath): boolean {
  return path.summary.trim().length > 0 && (path.sourceUrl !== null || path.sourceLabel !== null);
}
